### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by samson-jerome** [tb2097/wacom-gui#1]
Hi,
This is a really handy tool, can I suggest two little features that could be handy:
- having a reset to default option (something that would just remove the config file)
- having an option to remove all assignment to the pad buttons (Users here often complain that here pressing buttons inadvertently and they usually end up putting some gaffer on the pad !)

If I can find some time, I'll try to implement these, if anyone can that'd be great !
Thanks for the effort and sharing.

**Comment by tb2097** [comment]
The "quick fix" to reset to default would be to just remove the config file, but it would require the user to log out before settings would reset.  The cleaner method would be to ensure all buttons are reset to default values, touch is re-enabled, pressure curve set to default, etc.  The functionality shouldn't be too difficult to implement once I have time.

Removing pad button configs would probably be easiest to implement as a subset of the "reset defaults" function.  We are currently in an artist ramp up phase right now so I don't have much free time but I will get on this in the next month or so after the initial wave is passed (need test hardware to dev test at home).

**Comment by tb2097** [comment]
Released updated version 0.1.7; contains requested features and adds PTH-660 tablet along with a few other bug fixes.
