### ISSUE TITLE
Where to get PyQt4-webkit for ubuntu ?

### ISSUE THREAD

**Issue by Garrom** [tb2097/wacom-gui#22]
I can't find anywhere PyQt4-webkit for Ubuntu 18.04 so I'm unable to launch application. Do anyone knows where to find it ?

**Comment by tb2097** [comment]
sudo apt-get install python2.7-pyside.qtwebkit

Although I would suggest using the newer beta version of the GUI as it is significantly better. It shouldn't have the requirement for webkit.

**Comment by Garrom** [comment]
> sudo apt-get install python2.7-pyside.qtwebkit
> 
> Although I would suggest using the newer beta version of the GUI as it is significantly better. It shouldn't have the requirement for webkit.

Terminal says that it cannot find it. I'm probably missing PPA. Anyway, where is mentioned beta ? I'm kinda new to all this git (not exactly new but I'm not using it much) so I probably missed it.

**Comment by tb2097** [comment]
It is the latest release: https://github.com/tb2097/wacom-gui/releases
