### ISSUE TITLE
Map Tilde Key

### ISSUE THREAD

**Issue by Aamir-Raza** [tb2097/wacom-gui#36]
Hi,

Not sure if this is some kind of limitation or a bug but every time I try to map the tilde key onto a Wacom pad button it doesn't seem to work. 

Intuos Pro Medium (PTH-651)
CentOS Linux release 7.6.1810

Any ideas? thanks 😃

**Comment by tb2097** [comment]
This was a fun one-liner that I probably should have caught in testing.  I'll put the patch into the next release.

keymap.json:
-  		"lshift `": "~"
+ 		"lshift grave": "~"

**Comment by Aamir-Raza** [comment]
Cool thanks! :)
