### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by noloop** [tb2097/wacom-gui#48]
I tried run with the step:

download the source, run wacom-gui.py from the wacom-gui directory

And I get:

```
./wacom-gui/wacom-gui/wacom-gui.py", line 194
    print e
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(e)?
```

Easy to solve of course, change the code `print e` to `print(e)`

**Comment by JojiiOfficial** [comment]
Thats a python version problem, not a code issue. Use python2.
