### ISSUE TITLE
Sourcing  ~/.wacom-gui.sh from ~/.bashrc - not a good idea?

### ISSUE THREAD

**Issue by jcpearson** [tb2097/wacom-gui#5]
Running X11 specific commands (xsetwacom and xinput) from ~/.bashrc is not a good idea ...

This sort of thing should really be run from an autostart .desktop file - I would suggest either creating or copying in a suitable desktop file to ~/.config/autostart/ that execs ~/.wacom-gui.sh instead?

**Comment by tb2097** [comment]
The current method in bashrc only runs if an x session is running, so it shouldn't cause an issue.  I'll look at setting up a .desktop file instead as it's probably a cleaner implementation so I <i>will</i> get around to it, but it might be a little while.

**Comment by jcpearson** [comment]
I've already hacked things so a system-wide (via /etc/xdg/autostart/) desktop file is used to to run 'wacom-gui --load' - and nothing is added to ~/.bashrc

I also have a number of other hacks/tweaks/additions that we're using - which you might be interested in ... although I'm not sure the best way to send them to you ?

**Comment by jcpearson** [comment]
I've uploaded a SRPM and README file ... hopefully it's all self explanatory

**Comment by tb2097** [comment]
Got a chance to look at the README and they seem to all make sense for fixes.  It'll take me a little bit to poke through and verify it doesn't break anything that I can see but I definitely appreciate you testing/adding additional tablets as well as a few options I didn't really think of adding in.

**Comment by tb2097** [comment]
Rolled most of the fixes into place; trying to do a more elegant fix for disabling pad buttons and saving prefs.  I want to configure it to eventually allow for saving multiple prefs for a given tablet (artists might have a preference based on a given app) and it'll also allow for eventually allowing multiple tablets to be connected at once and load their profiles all at the same time.  I was going to save the updated release until the fixes were in place but if you'd like them sooner please let me know.

**Comment by jcpearson** [comment]
Thanks - if you can come up with a better way of disabling pad buttons then I would like to test that

**Comment by jcpearson** [comment]
(didn't mean to close this!)

**Comment by tb2097** [comment]
All fixes/tweaks added to release - thanks for providing/testing this!  Let me know if the improved enable/disable works well. https://github.com/tb2097/wacom-gui/releases/tag/V0.2.0

**Comment by jcpearson** [comment]
Thanks - the enable/disable buttons feature is nice

I didn't have PyQt4-webkit/qtwebkit installed as they are not part of standard RHEL/CentOS 7 - but not  really an issue, as I already have Mate from EPEL anyway ...

I've found a couple of minor problems - for which I'll open new 'issues' (so as to not to confuse things here ...)

**Comment by tb2097** [comment]
Most people who are running MATE on CentOS are running the EPEL repo as well, although I'll add a note on the main page about it being required.  I think it makes the help considerably cleaner than just a text field.

I'll close off this ticket as it's kind of strayed from the original issue but the fixes for it have been addressed through the update.
