### ISSUE TITLE
'tar' file in v0.2.0d SRPM is actually a 'zip' file

### ISSUE THREAD

**Issue by jcpearson** [tb2097/wacom-gui#7]
Not a major issue, as rpmbuild appears to cope with it OK, but the source file 'wacom-gui-0.2.0d.tar.gz' in the 0.2.0d SRPM is not a compressed tar file, but actually a zip file ... which is a bit confusing :-)

**Comment by tb2097** [comment]
Fixed in newer release.  Renaming a *.zip to *.tar.gz doesn't make a difference to the RPM build process but I'll try to make sure a tar.gz is not really a zip with future releases.
